#pragma once
// Stub DirectInput — input real via SDL no port Linux.
#include <d3d9.h>
#include "win32_extras.h"

#ifndef DIRECTINPUT_VERSION
#define DIRECTINPUT_VERSION 0x0800
#endif

struct IDirectInput8A;
struct IDirectInputDevice8A;
using IDirectInput8 = IDirectInput8A;
using IDirectInputDevice8 = IDirectInputDevice8A;
using LPDIRECTINPUT8 = IDirectInput8A*;
using LPDIRECTINPUTDEVICE8 = IDirectInputDevice8A*;
using LPDIRECTINPUT8A = IDirectInput8A*;
using LPDIRECTINPUTDEVICE8A = IDirectInputDevice8A*;

using LPDIENUMDEVICESCALLBACK = BOOL(CALLBACK*)(void*, LPVOID);
using LPDIENUMDEVICESCALLBACKA = LPDIENUMDEVICESCALLBACK;
using LPDIENUMDEVICESCALLBACKW = LPDIENUMDEVICESCALLBACK;
using LPDIENUMDEVICEOBJECTSCALLBACK = BOOL(CALLBACK*)(void*, LPVOID);
using LPDIENUMDEVICEOBJECTSCALLBACKA = LPDIENUMDEVICEOBJECTSCALLBACK;
using LPDIENUMDEVICEOBJECTSCALLBACKW = LPDIENUMDEVICEOBJECTSCALLBACK;
using LPDIENUMEFFECTSCALLBACK = BOOL(CALLBACK*)(void*, LPVOID);
using LPDIENUMEFFECTSCALLBACKA = LPDIENUMEFFECTSCALLBACK;
using LPDIENUMEFFECTSCALLBACKW = LPDIENUMEFFECTSCALLBACK;
using LPDIENUMCREATEDEFFECTOBJECTSCALLBACK = BOOL(CALLBACK*)(void*, LPVOID);
using LPDIENUMEFFECTSINFILECALLBACK = BOOL(CALLBACK*)(void*, LPVOID);
using LPDICONFIGUREDEVICESCALLBACK = BOOL(CALLBACK*)(void*, LPVOID);

struct DIMOUSESTATE2 {
	LONG lX, lY, lZ;
	BYTE rgbButtons[8];
};
struct DIJOYSTATE2 {
	LONG lX, lY, lZ, lRx, lRy, lRz;
	LONG rglSlider[2];
	DWORD rgdwPOV[4];
	BYTE rgbButtons[128];
};

#define DI_OK 0
#define DI8DEVCLASS_ALL 0
#define DISCL_FOREGROUND 0x1
#define DISCL_NONEXCLUSIVE 0x2
#define DISCL_BACKGROUND 0x8
#define DIDFT_ALL 0
#define DIK_ESCAPE 0x01

inline HRESULT DirectInput8Create(HINSTANCE, DWORD, REFIID, LPVOID*, LPUNKNOWN) { return E_NOTIMPL; }
